version: "2.1"

services:
  postgres:
    image: postgres:latest

    healthcheck:
      test: "pg_isready -p ${TG_DB_PORT} -q -d ${TG_DB_DATABASE} -U ${TG_DB_USER}"
      interval: 20s
      timeout: 60s
      retries: 8

    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./db_scripts:/docker-entrypoint-initdb.d

    ports:
      - "${TG_DB_PORT}:5432"

    environment:
      - TG_ENVIRONMENT=DEVELOPMENT

      - POSTGRES_USER=${TG_DB_USER}
      - POSTGRES_PASSWORD=${TG_DB_PASSWORD}
      - POSTGRES_DB=${TG_DB_DATABASE}
