interface IChannelsNames {
    [key: string]: string;
}

export const channelsNames: IChannelsNames = {
    '1TV': '1tv',
    '2X2': '2x2',
    'boets': 'boets',
    'Che': 'che',
    'Disney': 'disney',
    'DOMASHNIY': 'domashniy',
    'DomKino': 'domkino',
    'Drive_MTU': 'drive',
    'Explorer': 'explorer',
    'FOX LIFE': 'foxlife',
    'Friday': 'friday',
    'Ha&Fi_MTU': 'ohota',
    'History': 'history',
    'JiVi': 'jivi',
    'Karusel': 'karusel',
    'Kuhna': 'kuhna',
    'KUL': 'kultura',
    'MatchTV': 'matchtv',
    'ntv+9': 'khl',
    'ntv+13': 'eurosport',
    'ntv+16': 'discovery',
    'ntv+17': 'animalplanet',
    'ntv+20': 'natgeo',
    'NTV': 'ntv',
    'OTR': 'otr',
    'Piter5_RUS': '5kanal',
    'RAIN': 'rain',
    'RBK': 'rbk',
    'Reality': 'reality',
    'RenTV_REG': 'ren',
    'Retro_MTU': 'retro',
    'RTR': 'rossia',
    'RU_ILLusio': 'ruillusion',
    'SET_RUSSIA': 'sony',
    'STS': 'sts',
    'TDK': 'tdk',
    'TLC': 'tlc',
    'TNT0': 'tnt',
    'TV3_REG': 'tv3',
    'TV21': 'tv21',
    'TV1000': 'tv1000',
    'TV1000_RK': 'tv1000rk',
    'TVC': 'tvc',
    'U': 'u',
    'Usadba_MTU': 'usadba',
    'Zdorov_MTU': 'zdorovoe',
    'ZVEZDA': 'zvezda',
};
